<?php
$title = 'Add new Brand';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('brand', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('text'));
echo $this->formRow($form->get('web'));
echo $this->formRow($form->get('img'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();