<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit band';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'band',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('website'));
echo $this->formRow($form->get('info'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();