<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sRigmachine%s'), '<span class="zf-red">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('blablabla')) ?></p>
    <p><a class="btn btn-success btn-large" href="#" target="_blank"><?php echo $this->translate('Ir a cualquierparte') ?> &raquo;</a></p>
</div>

<div class="row">
    <div class="span4">
        <h2><?php echo $this->translate('Wopwop') ?></h2>
        <p>wopwop</p>
    </div>
</div>
